# Generated by Django 3.2.7 on 2021-09-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0004_alter_people_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
